const express = require('express');
const app = express();
const dotenv = require("dotenv");
dotenv.config();
const mongoose = require("mongoose");
const ToDoTask = require("./models/TodoTask.js");
const port = 3000;

app.use(express.urlencoded({ extended: true }));
// Middleware :- 
// express.static is a middleware function built in Express that serves static files such as 
// images, CSS files, and JavaScript files located in a directory called public.
app.use("/static", express.static("public"));

mongoose.connect(process.env.DB_CONNECT, { useNewUrlParser: true })
    .then(() => {
        console.log("Connected to the database");
        app.listen(port, () => {
            console.log("Server up and running");
        });
    })
    .catch((err) => {
        console.error(err);
    });

// This specifies the template engine to use, in this case ejs.
app.set("view engine", "ejs");

app.get('/', (req, res) => {
    // This uses the render method of the response object to allow the call back function 
    // to return the rendering of the HTML generated by the EJS template engine.
    res.render('todo.ejs');
});

app.post('/', async (req, res) => {
    const todoTask = new ToDoTask({
        content: req.body.content,
    });
    try {
        await todoTask.save();
        res.redirect("/");
    }
    catch (err) {
        res.send(500, error);
        res.redirect('/');
    }
});


