const express = require('express');
const app = express();
app.use(express.urlencoded({ extended: true }));
const port = 3000;

// Middleware :- 
// express.static is a middleware function built in Express that serves static files such as images, CSS files, and JavaScript files located in a directory called public.
app.use("/static", express.static("public"));

// This specifies the template engine to use, in this case ejs.
app.set("view engine", "ejs");

app.get('/', (req, res) => {
    // This uses the render method of the response object to allow the call back function to return the rendering of the HTML generated by the EJS template engine.
    res.render('todo.ejs');
});

app.post('/', (req, res) => {
    console.log(req.body);
});

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});

